use_frameworks!

platform :ios, '10.0'
source 'https://github.com/LuShanshan633/LSSSpecs.git'

target 'LSSWarToAmr_Example' do
  pod 'LSSWarToAmr', :path => '../'

  target 'LSSWarToAmr_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
