use_frameworks!

platform :ios, '8.0'

target 'LSSWarToAmr_Example' do
  pod 'LSSWarToAmr', :path => '../'

  target 'LSSWarToAmr_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
